name: Rubin Auto Fill (23:17 WIB)

on:
  schedule:
    - cron: "17 16 * * *"   # 23:17 WIB (WIB=UTC+7)
  workflow_dispatch: {}      # opsional

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        id: chrome

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install selenium webdriver-manager
          fi

      - name: Run bot
        env:
          RUBIN_EMAIL: ${{ secrets.RUBIN_EMAIL }}
          RUBIN_PASS:  ${{ secrets.RUBIN_PASS }}
        run: |
          set -e
          python bot.py 2>/dev/null || python main.py

      - name: Upload screenshots (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: |
            screenshots/**
            *.png
