name: Rubin Auto Fill

on:
  schedule:
    # WIB = UTC+7
    - cron: '5 13 * * *'   # 20:05 WIB
    - cron: '35 13 * * *'  # 20:35 WIB
    - cron: '5 14 * * *'   # 21:05 WIB
    - cron: '35 14 * * *'  # 21:35 WIB
  workflow_dispatch: {}    
jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          RUBIN_EMAIL: ${{ secrets.RUBIN_EMAIL }}
          RUBIN_PASS:  ${{ secrets.RUBIN_PASS }}
          CHROME_PATH: ${{ env.CHROME_PATH }}  
        run: |
          python bot.py

      - name: Upload screenshots (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: |
            *.png
